// <auto-generated />
namespace HypeTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class moreposters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moreposters));
        
        string IMigrationMetadata.Id
        {
            get { return "202104142359145_more-posters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
